global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-magento
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  reporting: true

tests:
  quickstart-magento-mysqlt1:
    parameter_input: quickstart-magento-mysqlt1.json
    template_file: magento-master.template
    regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2

  quickstart-magento-aurora1:
    parameter_input: quickstart-magento-aurora1.json
    template_file: magento-master.template
    regions:
    - ap-southeast-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
